### ISSUE TITLE
[Client] Implement developer-friendly client to use instead of raw commands

### ISSUE THREAD

**Issue by lisachenko** [lisachenko/protocol-fcgi#7]
Library provides only protocol implementation, which can be a stopper for new users, for example see #6.

Need to add high-level client implementation that encapsulates all this low-level stuff.

**Comment by AndrewCarterUK** [comment]
I'd recommend splitting this into a separate repository. You could have "server-fcgi" and "client-fcgi" which both depend on this repository.

**Comment by lisachenko** [comment]
@AndrewCarterUK I'd prefer to have them in one repo because creating a separate repo for each single client/server class is too much )

**Comment by AndrewCarterUK** [comment]
Two reasons I think for separating concerns:

The first (and least significant) is that your repository is named 'protocol-fcgi' and not 'fcgi'. So keeping it to protocol only logic makes a lot of sense.

The second is that you'll find the dependencies that you require to do a useful implementation of a server will very quickly grow beyond what you're comfortable putting in a lightweight library. Just going off the top of my head you'll probably want a console helper library and an event loop implementation. You'll also want support for PSR-7, HttpFoundation, etc. I've received complaints on my library that the basic server required PSR-7 and HttpFoundation and that they weren't optional plugins that were in separate repositories!

Good luck either way, just my 2 cents! :)

**Comment by lisachenko** [comment]
> The second is that you'll find the dependencies that you require to do a useful implementation of a server will very quickly grow beyond what you're comfortable putting in a lightweight library. Just going off the top of my head you'll probably want a console helper library and an event loop implementation. You'll also want support for PSR-7, HttpFoundation, etc.

It's valid point, agree with you.

**Comment by huyanping** [comment]
Looking forward

**Comment by lisachenko** [comment]
As I don't have enough time to support all my OSS packages, this will be up to developers to decide how to use this low-level library.
