### ISSUE TITLE
Packagist repository not updated

### ISSUE THREAD

**Issue by zamronypj** [lisachenko/protocol-fcgi#9]
Run

`composer require lisachenko/protocol-fcgi`

Open `vendor\lisachenko\composer.json`

```
    "autoload": {
        "psr-4" : {
            "Protocol\\" : "src/"
        }
    },

``` 

The content is not updated to latest version of Github repo

[composer.json](https://github.com/lisachenko/protocol-fcgi/blob/master/composer.json)
which use new namespace `"Lisachenko\\Protocol\\" : "src/"`

Which cause sample code in README.md failed.

**Comment by adawolfa** [comment]
You have stable (1.x) release installed, that's why.

@lisachenko Could you, please, tag 2.0.0? I've been using the development branch in ([adawolfa/fastcgi](https://packagist.org/packages/adawolfa/fastcgi)) for a while and everything seems to be OK.

**Comment by lisachenko** [comment]
Done, 2.0.0 tag is published.
